- hosts: single-node
  sudo: yes
  tasks:
          - name: Update apt-cache
            apt: update_cache=yes

          - name: Installing mesos
            apt: name=mesos state=latest

          - name: Installing Marathon
            apt: name=marathon state=latest

          - name: Installaind Docker
            apt: name=docker-engine state=latest

          - name: Starting zookeeper
            service: name=zookeeper state=started enabled=yes
                    
          - name: Starting mesos-master
            service: name=mesos-master state=started enabled=yes

          - name: Starting mesos-slave
            service: name=mesos-slave state=started enabled=yes

          - name: Starting marathon
            service: name=marathon state=started enabled=yes

          - name: Starting docker
            service: name=docker state=started enabled=yes

          - name: Add docker containerizer
            shell: echo 'docker,mesos' > /etc/mesos-slave/containerizers

          - name: Increase timeout to account for docker pull delay
            shell: echo '5mins' > /etc/mesos-slave/executor_registration_timeout

          - name: Restart mesos-slave
            service: name=mesos-slave state=restarted
